<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Offer Letter</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 13px; color: #111827; line-height: 1.6; }
        .header { border-bottom: 2px solid #111827; padding-bottom: 12px; margin-bottom: 28px; }
        .title { font-size: 24px; font-weight: bold; }
        .muted { color: #6b7280; }
        .box { background: #f9fafb; border: 1px solid #e5e7eb; padding: 14px; margin: 20px 0; }
        .footer { margin-top: 40px; font-size: 11px; color: #6b7280; border-top: 1px solid #d1d5db; padding-top: 12px; }
    </style>
</head>
<body>
    <div class="header">
        <div class="title">Offer Letter</div>
        <div class="muted">Generated on {{ now()->format('Y-m-d') }}</div>
    </div>

    <p>Dear {{ $candidate->full_name }},</p>

    <p>
        We are pleased to offer you the position of
        <strong>{{ $vacancy->title }}</strong>
        at our organization.
    </p>

    <div class="box">
        <p><strong>Position:</strong> {{ $vacancy->title }}</p>
        <p><strong>Employment Type:</strong> {{ $vacancy->employment_type ?? '-' }}</p>
        <p><strong>Department:</strong> {{ $vacancy->department ?? '-' }}</p>
        <p><strong>Location:</strong> {{ $vacancy->location ?? '-' }}</p>
    </div>

    <p>
        This offer is subject to completion of all required onboarding checks and submission of required documents.
    </p>

    <p>
        Please confirm your acceptance of this offer in writing.
    </p>

    <p>
        Kind regards,<br>
        HR Department
    </p>

    <div class="footer">
        Generated by Standalone HRM.
    </div>
</body>
</html>