<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Offer Letter</title>

    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
            font-size: 13px;
            color: #111827;
            line-height: 1.7;
        }

        .header {
            border-bottom: 2px solid #111827;
            padding-bottom: 14px;
            margin-bottom: 30px;
        }

        .title {
            font-size: 26px;
            font-weight: bold;
        }

        .muted {
            color: #6b7280;
        }

        .box {
            border: 1px solid #d1d5db;
            background: #f9fafb;
            padding: 14px;
            margin: 22px 0;
        }

        .signature {
            margin-top: 50px;
        }

        .footer {
            margin-top: 50px;
            border-top: 1px solid #d1d5db;
            padding-top: 12px;
            font-size: 11px;
            color: #6b7280;
        }
    </style>
</head>
<body>
    <div class="header">
        <div class="title">Offer Letter</div>
        <div class="muted">Generated on {{ now()->format('Y-m-d') }}</div>
    </div>

    <p>Dear {{ $candidate->full_name }},</p>

    <p>
        We are pleased to offer you the position of
        <strong>{{ $vacancy->title }}</strong>.
    </p>

    <div class="box">
        <p><strong>Candidate:</strong> {{ $candidate->full_name }}</p>
        <p><strong>Email:</strong> {{ $candidate->email }}</p>
        <p><strong>Position:</strong> {{ $vacancy->title }}</p>
        <p><strong>Department:</strong> {{ $vacancy->department ?? 'Not specified' }}</p>
        <p><strong>Location:</strong> {{ $vacancy->location ?? 'Not specified' }}</p>
        <p><strong>Employment Type:</strong> {{ $vacancy->employment_type ?? 'Not specified' }}</p>
    </div>

    <p>
        This offer is subject to successful completion of all required onboarding checks
        and submission of required employment documentation.
    </p>

    <p>
        Please confirm your acceptance of this offer in writing.
    </p>

    <div class="signature">
        <p>
            Kind regards,<br>
            <strong>HR Department</strong>
        </p>
    </div>

    <div class="footer">
        Generated by Standalone HRM.
    </div>
</body>
</html>