<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $template->name }}</title>

    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
            font-size: 13px;
            color: #111827;
            line-height: 1.7;
        }

        .header {
            border-bottom: 2px solid #111827;
            padding-bottom: 14px;
            margin-bottom: 28px;
        }

        .company {
            font-size: 22px;
            font-weight: bold;
        }

        .muted {
            color: #6b7280;
            font-size: 11px;
        }

        .content {
            white-space: pre-line;
        }

        .signature-block {
            margin-top: 55px;
        }

        .signature-image {
            max-width: 180px;
            max-height: 75px;
            margin-bottom: 6px;
        }

        .signature-line {
            border-top: 1px solid #111827;
            width: 240px;
            margin-top: 10px;
            padding-top: 6px;
        }

        .footer {
            margin-top: 50px;
            border-top: 1px solid #d1d5db;
            padding-top: 10px;
            font-size: 10px;
            color: #6b7280;
        }
    </style>
</head>
<body>
    <div class="header">
        <div class="company">{{ $company->company_name }}</div>

        @if($company->company_address)
            <div class="muted">{{ $company->company_address }}</div>
        @endif

        @if($company->company_email || $company->company_phone)
            <div class="muted">
                {{ $company->company_email }}
                @if($company->company_email && $company->company_phone)
                    |
                @endif
                {{ $company->company_phone }}
            </div>
        @endif
    </div>

    <div class="content">
        {!! nl2br(e($content)) !!}
    </div>

    <div class="signature-block">
        @if($company->ceo_signature_path)
            <img src="{{ public_path('storage/' . $company->ceo_signature_path) }}"
                 class="signature-image">
        @endif

        <div class="signature-line">
            <strong>{{ $company->ceo_name }}</strong><br>
            {{ $company->ceo_title }}<br>
            {{ $company->company_name }}
        </div>
    </div>

    <div class="footer">
        Generated by Standalone HRM on {{ now()->format('d M Y H:i') }}.
    </div>
</body>
</html>