<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Employment Confirmation</title>

    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
            color: #111827;
            font-size: 13px;
            line-height: 1.7;
        }

        .header {
            border-bottom: 2px solid #111827;
            padding-bottom: 14px;
            margin-bottom: 30px;
        }

        .title {
            font-size: 24px;
            font-weight: bold;
        }

        .muted {
            color: #6b7280;
        }

        .box {
            border: 1px solid #d1d5db;
            background: #f9fafb;
            padding: 14px;
            margin: 22px 0;
        }

        .footer {
            margin-top: 50px;
            border-top: 1px solid #d1d5db;
            padding-top: 12px;
            font-size: 11px;
            color: #6b7280;
        }
    </style>
</head>
<body>
    <div class="header">
        <div class="title">Employment Confirmation Letter</div>
        <div class="muted">Generated on {{ now()->format('Y-m-d') }}</div>
    </div>

    <p>To whom it may concern,</p>

    <p>
        This letter confirms that <strong>{{ $employee->full_name }}</strong>
        is employed by our organization.
    </p>

    <div class="box">
        <p><strong>Employee Number:</strong> {{ $employee->employee_number }}</p>
        <p><strong>Job Title:</strong> {{ $employee->job_title ?? 'Not specified' }}</p>
        <p><strong>Employment Type:</strong> {{ $employee->employment_type ?? 'Not specified' }}</p>
        <p><strong>Employment Status:</strong> {{ ucfirst($employee->status) }}</p>
        <p><strong>Hire Date:</strong> {{ $employee->hire_date?->format('Y-m-d') ?? 'Not specified' }}</p>
    </div>

    <p>
        This confirmation is generated from the Standalone HRM system based on the employee records currently available.
    </p>

    <p>
        Kind regards,<br>
        HR Department
    </p>

    <div class="footer">
        Generated by Standalone HRM.
    </div>
</body>
</html>