<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Payslip {{ $payslip->period }}</title>

    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
            font-size: 13px;
            color: #111827;
        }

        .header {
            border-bottom: 2px solid #111827;
            padding-bottom: 12px;
            margin-bottom: 24px;
        }

        .title {
            font-size: 24px;
            font-weight: bold;
        }

        .muted {
            color: #6b7280;
        }

        .grid {
            width: 100%;
            margin-bottom: 24px;
        }

        .grid td {
            padding: 6px 0;
        }

        table.pay {
            width: 100%;
            border-collapse: collapse;
            margin-top: 12px;
        }

        table.pay th,
        table.pay td {
            border: 1px solid #d1d5db;
            padding: 10px;
        }

        table.pay th {
            background: #f3f4f6;
            text-align: left;
        }

        .right {
            text-align: right;
        }

        .net {
            font-size: 18px;
            font-weight: bold;
            background: #ecfdf5;
        }

        .footer {
            margin-top: 32px;
            font-size: 11px;
            color: #6b7280;
            border-top: 1px solid #d1d5db;
            padding-top: 12px;
        }
    </style>
</head>
<body>
    <div class="header">
        <div class="title">Payslip</div>
        <div class="muted">Period: {{ $payslip->period }}</div>
    </div>

    <table class="grid">
        <tr>
            <td><strong>Employee:</strong> {{ $payslip->employee->full_name }}</td>
            <td><strong>Employee No:</strong> {{ $payslip->employee->employee_number }}</td>
        </tr>
        <tr>
            <td><strong>Status:</strong> {{ ucfirst($payslip->status) }}</td>
            <td><strong>Generated:</strong> {{ now()->format('Y-m-d') }}</td>
        </tr>
    </table>

    <table class="pay">
        <thead>
            <tr>
                <th>Description</th>
                <th class="right">Amount</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>Basic Salary</td>
                <td class="right">{{ number_format($payslip->basic_salary, 2) }}</td>
            </tr>
            <tr>
                <td>Allowances</td>
                <td class="right">{{ number_format($payslip->allowances, 2) }}</td>
            </tr>
            <tr>
                <td>Deductions</td>
                <td class="right">-{{ number_format($payslip->deductions, 2) }}</td>
            </tr>
            <tr>
                <td>Tax</td>
                <td class="right">-{{ number_format($payslip->tax, 2) }}</td>
            </tr>
            <tr class="net">
                <td>Net Pay</td>
                <td class="right">{{ number_format($payslip->net_pay, 2) }}</td>
            </tr>
        </tbody>
    </table>

    @if ($payslip->notes)
        <p><strong>Notes:</strong> {{ $payslip->notes }}</p>
    @endif

    <div class="footer">
        This payslip was generated by Standalone HRM.
    </div>
</body>
</html>